from Tkinter import *
class GUI(Frame):
    def __init__(self, master):
        Frame.__init__(self, master)
        self.master=master
        
    def smallGUI(self):
        
        
        l01 = Label(self.master, text=" 1")
        l01.grid(row=0, column=1, sticky=W)
        l02 = Label(self.master, text=" 1")
        l02.grid(row=0, column=2, sticky=W)
        l03 = Label(self.master, text=" 1")
        l03.grid(row=0, column=3, sticky=W)
        l04 = Label(self.master, text=" 1")
        l04.grid(row=0, column=4, sticky=W)
        l05 = Label(self.master, text=" 1")
        l05.grid(row=0, column=5, sticky=W)
        l06 = Label(self.master, text=" 1")
        l06.grid(row=0, column=6, sticky=W)
        
        l10 = Label(self.master, text=" 1")
        l10.grid(row=1, column=0, sticky=W)
        
        c11 = Checkbutton(self.master)
        c11.grid(row=1, column=1, sticky=W)
        v11=IntVar()
        c12 = Checkbutton(self.master, variable=v11)
        c12.grid(row=1, column=2, sticky=W)
        c13 = Checkbutton(self.master)
        c13.grid(row=1, column=3, sticky=W)
        c14 = Checkbutton(self.master)
        c14.grid(row=1, column=4, sticky=W)
        c15 = Checkbutton(self.master)
        c15.grid(row=1, column=5, sticky=W)
        c16 = Checkbutton(self.master)
        c16.grid(row=1, column=6, sticky=W)
        
        

        l20 = Label(self.master, text="1")
        l20.grid(row=2, column=0, sticky=W)
        c21 = Checkbutton(self.master)
        c21.grid(row=2, column=1, sticky=W)
        c22 = Checkbutton(self.master)
        c22.grid(row=2, column=2, sticky=W)
        c23 = Checkbutton(self.master)
        c23.grid(row=2, column=3, sticky=W)
        c24 = Checkbutton(self.master)
        c24.grid(row=2, column=4, sticky=W)
        c25 = Checkbutton(self.master)
        c25.grid(row=2, column=5, sticky=W)
        c26 = Checkbutton(self.master)
        c26.grid(row=2, column=6, sticky=W)
      

        l30 = Label(self.master, text="1")
        l30.grid(row=3, column=0, sticky=W)
        c31 = Checkbutton(self.master)
        c31.grid(row=3, column=1, sticky=W)
        c32 = Checkbutton(self.master)
        c32.grid(row=3, column=2, sticky=W)
        c33 = Checkbutton(self.master)
        c33.grid(row=3, column=3, sticky=W)
        c34 = Checkbutton(self.master)
        c34.grid(row=3, column=4, sticky=W)
        c35 = Checkbutton(self.master)
        c35.grid(row=3, column=5, sticky=W)
        c36 = Checkbutton(self.master)
        c36.grid(row=3, column=6, sticky=W)
       

        l40 = Label(self.master, text="1")
        l40.grid(row=4, column=0, sticky=W)
        c41 = Checkbutton(self.master)
        c41.grid(row=4, column=1, sticky=W)
        c42 = Checkbutton(self.master)
        c42.grid(row=4, column=2, sticky=W)
        c43 = Checkbutton(self.master)
        c43.grid(row=4, column=3, sticky=W)
        c44 = Checkbutton(self.master)
        c44.grid(row=4, column=4, sticky=W)
        c45 = Checkbutton(self.master)
        c45.grid(row=4, column=5, sticky=W)
        c46 = Checkbutton(self.master)
        c46.grid(row=4, column=6, sticky=W)
        

        l50 = Label(self.master, text="1")
        l50.grid(row=5, column=0, sticky=W)
        c51 = Checkbutton(self.master)
        c51.grid(row=5, column=1, sticky=W)
        c52 = Checkbutton(self.master)
        c52.grid(row=5, column=2, sticky=W)
        c53 = Checkbutton(self.master)
        c53.grid(row=5, column=3, sticky=W)
        c54 = Checkbutton(self.master)
        c54.grid(row=5, column=4, sticky=W)
        c55 = Checkbutton(self.master)
        c55.grid(row=5, column=5, sticky=W)
        c56 = Checkbutton(self.master)
        c56.grid(row=5, column=6, sticky=W)
        
        
        l60 = Label(self.master, text="1")
        l60.grid(row=6, column=0, sticky=W)
        c61 = Checkbutton(self.master)
        c61.grid(row=6, column=1, sticky=W)
        c62 = Checkbutton(self.master)
        c62.grid(row=6, column=2, sticky=W)
        c63 = Checkbutton(self.master)
        c63.grid(row=6, column=3, sticky=W)
        c64 = Checkbutton(self.master)
        c64.grid(row=6, column=4, sticky=W)
        c65 = Checkbutton(self.master)
        c65.grid(row=6, column=5, sticky=W)
        c66 = Checkbutton(self.master)
        c66.grid(row=6, column=6, sticky=W)

        Button(self.master, text='Check', command=smallGUI).grid(row=7, sticky=W, pady=8)
    print("male: %d" % (v11.get()))
        
        

    def bigGUI(self):
        
        l01 = Label(self.master, text=" 1")
        l01.grid(row=0, column=1, sticky=W)
        l02 = Label(self.master, text=" 1")
        l02.grid(row=0, column=2, sticky=W)
        l03 = Label(self.master, text=" 1")
        l03.grid(row=0, column=3, sticky=W)
        l04 = Label(self.master, text=" 1")
        l04.grid(row=0, column=4, sticky=W)
        l05 = Label(self.master, text=" 1")
        l05.grid(row=0, column=5, sticky=W)
        l06 = Label(self.master, text=" 1")
        l06.grid(row=0, column=6, sticky=W)
        l07 = Label(self.master, text=" 1")
        l07.grid(row=0, column=7, sticky=W)
        l08 = Label(self.master, text=" 1")
        l08.grid(row=0, column=8, sticky=W)
        l10 = Label(self.master, text=" 1")
        l10.grid(row=1, column=0, sticky=W)
        c11 = Checkbutton(self.master)
        c11.grid(row=1, column=1, sticky=W)
        c12 = Checkbutton(self.master)
        c12.grid(row=1, column=2, sticky=W)
        c13 = Checkbutton(self.master)
        c13.grid(row=1, column=3, sticky=W)
        c14 = Checkbutton(self.master)
        c14.grid(row=1, column=4, sticky=W)
        c15 = Checkbutton(self.master)
        c15.grid(row=1, column=5, sticky=W)
        c16 = Checkbutton(self.master)
        c16.grid(row=1, column=6, sticky=W)
        c17 = Checkbutton(self.master)
        c17.grid(row=1, column=7, sticky=W)
        c18 = Checkbutton(self.master)
        c18.grid(row=1, column=8, sticky=W)
        l20 = Label(self.master, text="1")
        l20.grid(row=2, column=0, sticky=W)
        c21 = Checkbutton(self.master)
        c21.grid(row=2, column=1, sticky=W)
        c22 = Checkbutton(self.master)
        c22.grid(row=2, column=2, sticky=W)
        c23 = Checkbutton(self.master)
        c23.grid(row=2, column=3, sticky=W)
        c24 = Checkbutton(self.master)
        c24.grid(row=2, column=4, sticky=W)
        c25 = Checkbutton(self.master)
        c25.grid(row=2, column=5, sticky=W)
        c26 = Checkbutton(self.master)
        c26.grid(row=2, column=6, sticky=W)
        c27 = Checkbutton(self.master)
        c27.grid(row=2, column=7, sticky=W)
        c28 = Checkbutton(self.master)
        c28.grid(row=2, column=8, sticky=W)
        l30 = Label(self.master, text="1")
        l30.grid(row=3, column=0, sticky=W)
        c31 = Checkbutton(self.master)
        c31.grid(row=3, column=1, sticky=W)
        c32 = Checkbutton(self.master)
        c32.grid(row=3, column=2, sticky=W)
        c33 = Checkbutton(self.master)
        c33.grid(row=3, column=3, sticky=W)
        c34 = Checkbutton(self.master)
        c34.grid(row=3, column=4, sticky=W)
        c35 = Checkbutton(self.master)
        c35.grid(row=3, column=5, sticky=W)
        c36 = Checkbutton(self.master)
        c36.grid(row=3, column=6, sticky=W)
        c37 = Checkbutton(self.master)
        c37.grid(row=3, column=7, sticky=W)
        c38 = Checkbutton(self.master)
        c38.grid(row=3, column=8, sticky=W)
        l40 = Label(self.master, text="1")
        l40.grid(row=4, column=0, sticky=W)
        c41 = Checkbutton(self.master)
        c41.grid(row=4, column=1, sticky=W)
        c42 = Checkbutton(self.master)
        c42.grid(row=4, column=2, sticky=W)
        c43 = Checkbutton(self.master)
        c43.grid(row=4, column=3, sticky=W)
        c44 = Checkbutton(self.master)
        c44.grid(row=4, column=4, sticky=W)
        c45 = Checkbutton(self.master)
        c45.grid(row=4, column=5, sticky=W)
        c46 = Checkbutton(self.master)
        c46.grid(row=4, column=6, sticky=W)
        c47 = Checkbutton(self.master)
        c47.grid(row=4, column=7, sticky=W)
        c48 = Checkbutton(self.master)
        c48.grid(row=4, column=8, sticky=W)
        l50 = Label(self.master, text="1")
        l50.grid(row=5, column=0, sticky=W)
        c51 = Checkbutton(self.master)
        c51.grid(row=5, column=1, sticky=W)
        c52 = Checkbutton(self.master)
        c52.grid(row=5, column=2, sticky=W)
        c53 = Checkbutton(self.master)
        c53.grid(row=5, column=3, sticky=W)
        c54 = Checkbutton(self.master)
        c54.grid(row=5, column=4, sticky=W)
        c55 = Checkbutton(self.master)
        c55.grid(row=5, column=5, sticky=W)
        c56 = Checkbutton(self.master)
        c56.grid(row=5, column=6, sticky=W)
        c57 = Checkbutton(self.master)
        c57.grid(row=5, column=7, sticky=W)
        c58 = Checkbutton(self.master)
        c58.grid(row=5, column=8, sticky=W)
        l60 = Label(self.master, text="1")
        l60.grid(row=6, column=0, sticky=W)
        c61 = Checkbutton(self.master)
        c61.grid(row=6, column=1, sticky=W)
        c62 = Checkbutton(self.master)
        c62.grid(row=6, column=2, sticky=W)
        c63 = Checkbutton(self.master)
        c63.grid(row=6, column=3, sticky=W)
        c64 = Checkbutton(self.master)
        c64.grid(row=6, column=4, sticky=W)
        c65 = Checkbutton(self.master)
        c65.grid(row=6, column=5, sticky=W)
        c66 = Checkbutton(self.master)
        c66.grid(row=6, column=6, sticky=W)
        c67 = Checkbutton(self.master)
        c67.grid(row=6, column=7, sticky=W)
        c68 = Checkbutton(self.master)
        c68.grid(row=6, column=8, sticky=W)
        l70 = Label(self.master, text="1")
        l70.grid(row=7, column=0, sticky=W)
        c71 = Checkbutton(self.master)
        c71.grid(row=7, column=1, sticky=W)
        c72 = Checkbutton(self.master)
        c72.grid(row=7, column=2, sticky=W)
        c73 = Checkbutton(self.master)
        c73.grid(row=7, column=3, sticky=W)
        c74 = Checkbutton(self.master)
        c74.grid(row=7, column=4, sticky=W)
        c75 = Checkbutton(self.master)
        c75.grid(row=7, column=5, sticky=W)
        c76 = Checkbutton(self.master)
        c76.grid(row=7, column=6, sticky=W)
        c77 = Checkbutton(self.master)
        c77.grid(row=7, column=7, sticky=W)
        c78 = Checkbutton(self.master)
        c78.grid(row=7, column=8, sticky=W)
        l80 = Label(self.master, text="1")
        l80.grid(row=8, column=0, sticky=W)
        c81 = Checkbutton(self.master)
        c81.grid(row=8, column=1, sticky=W)
        c82 = Checkbutton(self.master)
        c82.grid(row=8, column=2, sticky=W)
        c83 = Checkbutton(self.master)
        c83.grid(row=8, column=3, sticky=W)
        c84 = Checkbutton(self.master)
        c84.grid(row=8, column=4, sticky=W)
        c85 = Checkbutton(self.master)
        c85.grid(row=8, column=5, sticky=W)
        c86 = Checkbutton(self.master)
        c86.grid(row=8, column=6, sticky=W)
        c87 = Checkbutton(self.master)
        c87.grid(row=8, column=7, sticky=W)
        c88 = Checkbutton(self.master)
        c88.grid(row=8, column=8, sticky=W)
        
        
        
        
window = Tk()
gui = GUI(window)
gui.smallGUI()
#gui.bigGUI()
window.mainloop()
